version: '3'
services:
    api:
        image: riteshmahato/python-fastapi
        depends_on:
            - postgres
        ports:
            - 80:8000
        #env_file:
         #   - ./.env
        environment:
            - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_USERNAME=${DATABASE_USERNAME}
            - SECRET_KEY=${SECRET_KEY}
            - ALGORITHM=${ALGORITHM}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    postgres:
        image: postgres
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust # Needed because we kept the password as empty
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db:

